components:
  schemas:
    GeneralError:
      type: object
      properties:
        data:
          type: any
        error:
          type: string
      example:
        data: null
        error: Something went wrong.
    NotFoundError:
      type: object
      properties:
        data:
          type: any
        error:
          type: string
      example:
        data: null
        error: Requested item not found.
    BadRequestError:
      type: object
      properties:
        data:
          type: any
        error:
          type: string
      example:
        data: null
        error: First name should not be empty.
    Task:
      type: object
      properties:
        heading:
          type: string
          example: Exam
        completed:
          type: boolean
          example: false
